version = 1

[[annotations]]
path = "bin/*"
SPDX-FileCopyrightText = "Copyright contributors to the sdl3_ada project."
SPDX-License-Identifier = "Zlib"

# Primarily included to satisfy REUSE.

[[annotations]]
path = ".gitignore"
SPDX-FileCopyrightText = "Copyright contributors to the sdl3_ada project."
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "README.md"
SPDX-FileCopyrightText = "Copyright contributors to the sdl3_ada project."
SPDX-License-Identifier = "CC0-1.0"


[[annotations]]
path = "alire/*"
SPDX-FileCopyrightText = "Copyright contributors to the sdl3_ada project."
SPDX-License-Identifier = "Zlib"

[[annotations]]
path = "config/*"
SPDX-FileCopyrightText = "Copyright contributors to the sdl3_ada project."
SPDX-License-Identifier = "Zlib"

[[annotations]]
path = "lib/*"
SPDX-FileCopyrightText = "Copyright contributors to the sdl3_ada project."
SPDX-License-Identifier = "Zlib"

[[annotations]]
path = "obj/*"
SPDX-FileCopyrightText = "Copyright contributors to the sdl3_ada project."
SPDX-License-Identifier = "Zlib"

[[annotations]]
path = "share/*"
SPDX-FileCopyrightText = "Copyright contributors to the sdl3_ada project."
SPDX-License-Identifier = "Zlib"
